#!/bin/bash
#!/data/data/com.termux/files/usr/bin/bash
URL="http://localhost:8081/xas?cmd=duk&src=./scr/usrproc.js"
URL="http://localhost:8081/xas?cmd=duk&src=./scr/srv.js"
URL="http://localhost:8081/xas?cmd=duk&src=./scr/sessions.js"
URL="http://localhost:8081/xas?cmd=duk&src=./scr/lsses.js"
URL="http://localhost:8081/xas?cmd=duk&src=./scr/dummy.js"
URL="http://localhost:8080/"
NREQ=65536
NCON=8
bombardier\
	-n $NREQ\
	-c $NCON\
	--header="Cookie: sessid=c1OFh"\
	$URL 
